# Generated by Django 5.1.2 on 2024-12-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriadorCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('cep', models.CharField(max_length=8)),
                ('perfil_campanha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('cep', models.CharField(max_length=8)),
                ('perfil_doacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=100)),
                ('perfil_campanha', models.CharField(max_length=100)),
            ],
        ),
    ]
