# Generated by Django 5.1.2 on 2024-12-18 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('perfil_doacao', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('descricao', models.TextField(max_length=400)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.criadorcampanha')),
                ('estabelecimentos', models.ManyToManyField(to='home.estabelecimento')),
            ],
        ),
    ]
