# Generated by Django 5.1.2 on 2024-12-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_campanha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='estabelecimentos',
        ),
        migrations.AddField(
            model_name='campanha',
            name='cnpj_estabelecimento',
            field=models.CharField(default=2, max_length=14),
            preserve_default=False,
        ),
    ]
