# Generated by Django 5.1.2 on 2024-12-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_campanha_estabelecimentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='estabelecimentos',
            field=models.CharField(default='', max_length=50),
        ),
    ]
