# Generated by Django 5.1.2 on 2024-12-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_campanha_estabelecimentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='estabelecimentos',
        ),
        migrations.AddField(
            model_name='campanha',
            name='estabelecimentos',
            field=models.ManyToManyField(null=True, to='home.estabelecimento'),
        ),
    ]
