# Generated by Django 5.1.2 on 2024-12-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_campanha_estabelecimentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='estabelecimentos',
            field=models.ManyToManyField(to='home.estabelecimento'),
        ),
    ]
