# Generated by Django 5.1.2 on 2024-12-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_campanha_estabelecimentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
