# Generated by Django 5.1.2 on 2024-12-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_campanha_cnpj_estabelecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='criadorcampanha',
            name='cidade',
            field=models.CharField(default='N/C', max_length=30),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='cep',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='cidade',
            field=models.CharField(default='N/C', max_length=30),
        ),
    ]
