# Generated by Django 5.1.2 on 2024-12-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_criadorcampanha_cidade_estabelecimento_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criadorcampanha',
            name='username',
            field=models.CharField(default='N/C', max_length=50),
        ),
    ]
